#pragma config(Motor,  port1,           portA1,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           portB1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           portB2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          portA2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(120)

typedef enum {UP, DOWN} UpDown;
//typedef enum {IN, OUT} InOut;
typedef enum {TANK, ARCADE} DriveStyle;

static bool const initial_belt_on = false;
//static bool const initial_chute_open = false;
static UpDown const initial_belt_direction = UP;
//static InOut const initial_chute_direction = OUT;

static DriveStyle const initial_drive_style = TANK;

static int const belt_btn = Btn7D;
static int const belt_sign_btn = Btn7R;
static int const chute_btn = Btn5D;
static int const chute_pve_btn = Btn6U;
static int const chute_nve_btn = Btn6D;
static int const chute_sign_btn = Btn5D;
static int const port_swap_btn = Btn8U;
static int const drive_style_btn = Btn7U;
static int const slow_mo_btn = Btn5U;
static int const stop_all_btn = Btn5D;

#include "ports.h"
#include "belt-chute.h"
#include "drive.h"
#include "button-events.h"
#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
	update_motors();
	stop_moving();

	while (true)
	{
		update_drive();
		check_buttons();
		motor[chute_motor] = (vexRT(chute_pve_btn)? 50 : 0) + (vexRT(chute_nve_btn)? -50 : 0);
	}
}
