#pragma config(Motor,  port1,           portA1,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           portB1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           portB2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          portA2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(120)

typedef enum {UP, DOWN} UpDown;
typedef enum {TANK, ARCADE} DriveStyle;

static bool const initial_belt_on = false;
static bool const initial_chute_on = false;
static UpDown const initial_belt_direction = UP;

static DriveStyle const initial_drive_style = TANK;

static TVexJoysticks const belt_btn = Btn7D;
static TVexJoysticks const belt_sign_btn = Btn7R;
static TVexJoysticks const chute_btn = Btn5D;
static TVexJoysticks const chute_pve_btn = Btn6U;
static TVexJoysticks const chute_nve_btn = Btn6D;
static TVexJoysticks const chute_sign_btn = Btn5D;
static TVexJoysticks const port_swap_btn = Btn8U;
static TVexJoysticks const drive_style_btn = Btn7U;
static TVexJoysticks const slow_mo_btn = Btn5U;
static TVexJoysticks const stop_all_btn = Btn5D;

#include "ports.h"
#include "belt-chute.h"
#include "drive.h"
#include "button-events.h"
#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
  update_motors();
  stop_moving();

  while (true)
  {
    update_drive();
    check_buttons();
    if (vexRT[chute_pve_btn] || vexRT[chute_nve_btn])
    {
    	chute_on = false;
    	update_motors();
    }
    if (!chute_on)
    {
    	motor[chute_motor] = (vexRT[chute_pve_btn]? 50 : 0) + (vexRT[chute_nve_btn]? -50 : 0);
    }
    if (vexRT[chute_pve_btn])
    {
    	belt_on = false;
    	update_motors();
    }
  }
}
